

package org.jetbrains.kotlin.formver.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.formver.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("formver.compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class PhasedDiagnosticTestGenerated extends AbstractPhasedDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("formver.compiler-plugin/testData/diagnostics/expensive_verification")
  @TestDataPath("$PROJECT_ROOT")
  public class Expensive_verification {
    @Test
    public void testAllFilesPresentInExpensive_verification() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/expensive_verification"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("backing_field_getters.kt")
    public void testBacking_field_getters() {
      runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/backing_field_getters.kt");
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms")
    @TestDataPath("$PROJECT_ROOT")
    public class Algorithms {
      @Test
      public void testAllFilesPresentInAlgorithms() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("binary_search.kt")
      public void testBinary_search() {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/binary_search.kt");
      }

      @Test
      @TestMetadata("merge_sort_of_string.kt")
      public void testMerge_sort_of_string() {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/merge_sort_of_string.kt");
      }

      @Test
      @TestMetadata("quick_sort_of_string.kt")
      public void testQuick_sort_of_string() {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/quick_sort_of_string.kt");
      }

      @Test
      @TestMetadata("z_function.kt")
      public void testZ_function() {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/z_function.kt");
      }
    }
  }

  @Nested
  @TestMetadata("formver.compiler-plugin/testData/diagnostics/locality_checker")
  @TestDataPath("$PROJECT_ROOT")
  public class Locality_checker {
    @Test
    public void testAllFilesPresentInLocality_checker() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/locality_checker"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("assign_local.kt")
    public void testAssign_local() {
      runTest("formver.compiler-plugin/testData/diagnostics/locality_checker/assign_local.kt");
    }

    @Test
    @TestMetadata("assign_property.kt")
    public void testAssign_property() {
      runTest("formver.compiler-plugin/testData/diagnostics/locality_checker/assign_property.kt");
    }

    @Test
    @TestMetadata("call.kt")
    public void testCall() {
      runTest("formver.compiler-plugin/testData/diagnostics/locality_checker/call.kt");
    }

    @Test
    @TestMetadata("call_with_context.kt")
    public void testCall_with_context() {
      runTest("formver.compiler-plugin/testData/diagnostics/locality_checker/call_with_context.kt");
    }

    @Test
    @TestMetadata("call_with_vararg.kt")
    public void testCall_with_vararg() {
      runTest("formver.compiler-plugin/testData/diagnostics/locality_checker/call_with_vararg.kt");
    }

    @Test
    @TestMetadata("default_argument.kt")
    public void testDefault_argument() {
      runTest("formver.compiler-plugin/testData/diagnostics/locality_checker/default_argument.kt");
    }

    @Test
    @TestMetadata("invalid.kt")
    public void testInvalid() {
      runTest("formver.compiler-plugin/testData/diagnostics/locality_checker/invalid.kt");
    }

    @Test
    @TestMetadata("nested_scope.kt")
    public void testNested_scope() {
      runTest("formver.compiler-plugin/testData/diagnostics/locality_checker/nested_scope.kt");
    }

    @Test
    @TestMetadata("return.kt")
    public void testReturn() {
      runTest("formver.compiler-plugin/testData/diagnostics/locality_checker/return.kt");
    }

    @Test
    @TestMetadata("throw.kt")
    public void testThrow() {
      runTest("formver.compiler-plugin/testData/diagnostics/locality_checker/throw.kt");
    }
  }

  @Nested
  @TestMetadata("formver.compiler-plugin/testData/diagnostics/stdlib")
  @TestDataPath("$PROJECT_ROOT")
  public class Stdlib {
    @Test
    public void testAllFilesPresentInStdlib() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/stdlib"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("stdlib_replacement_tests.kt")
    public void testStdlib_replacement_tests() {
      runTest("formver.compiler-plugin/testData/diagnostics/stdlib/stdlib_replacement_tests.kt");
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/stdlib/list")
    @TestDataPath("$PROJECT_ROOT")
    public class List {
      @Test
      public void testAllFilesPresentInList() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/stdlib/list"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("binary_search.kt")
      public void testBinary_search() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/list/binary_search.kt");
      }

      @Test
      @TestMetadata("custom_list.kt")
      public void testCustom_list() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/list/custom_list.kt");
      }

      @Test
      @TestMetadata("list.kt")
      public void testList() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/list/list.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/stdlib/string")
    @TestDataPath("$PROJECT_ROOT")
    public class String {
      @Test
      public void testAllFilesPresentInString() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/stdlib/string"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("chars.kt")
      public void testChars() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/string/chars.kt");
      }

      @Test
      @TestMetadata("strings.kt")
      public void testStrings() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/string/strings.kt");
      }
    }
  }

  @Nested
  @TestMetadata("formver.compiler-plugin/testData/diagnostics/uniqueness_checker")
  @TestDataPath("$PROJECT_ROOT")
  public class Uniqueness_checker {
    @Test
    public void testAllFilesPresentInUniqueness_checker() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/uniqueness_checker"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("annotations.kt")
    public void testAnnotations() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/annotations.kt");
    }

    @Test
    @TestMetadata("assign_local.kt")
    public void testAssign_local() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/assign_local.kt");
    }

    @Test
    @TestMetadata("assign_property.kt")
    public void testAssign_property() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/assign_property.kt");
    }

    @Test
    @TestMetadata("borrow_local.kt")
    public void testBorrow_local() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/borrow_local.kt");
    }

    @Test
    @TestMetadata("borrow_property.kt")
    public void testBorrow_property() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/borrow_property.kt");
    }

    @Test
    @TestMetadata("consume_deeply_nested.kt")
    public void testConsume_deeply_nested() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/consume_deeply_nested.kt");
    }

    @Test
    @TestMetadata("consume_local.kt")
    public void testConsume_local() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/consume_local.kt");
    }

    @Test
    @TestMetadata("consume_property.kt")
    public void testConsume_property() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/consume_property.kt");
    }

    @Test
    @TestMetadata("dump_cfg.kt")
    public void testDump_cfg() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/dump_cfg.kt");
    }

    @Test
    @TestMetadata("pass_local_argument.kt")
    public void testPass_local_argument() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/pass_local_argument.kt");
    }

    @Test
    @TestMetadata("pass_property_argument.kt")
    public void testPass_property_argument() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/pass_property_argument.kt");
    }

    @Test
    @TestMetadata("return_local.kt")
    public void testReturn_local() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/return_local.kt");
    }

    @Test
    @TestMetadata("return_property.kt")
    public void testReturn_property() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/return_property.kt");
    }

    @Test
    @TestMetadata("share_local.kt")
    public void testShare_local() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/share_local.kt");
    }

    @Test
    @TestMetadata("share_property.kt")
    public void testShare_property() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/share_property.kt");
    }

    @Test
    @TestMetadata("throw_local.kt")
    public void testThrow_local() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/throw_local.kt");
    }

    @Test
    @TestMetadata("throw_property.kt")
    public void testThrow_property() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/throw_property.kt");
    }
  }

  @Nested
  @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification")
  @TestDataPath("$PROJECT_ROOT")
  public class Verification {
    @Test
    public void testAllFilesPresentInVerification() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("basic.kt")
    public void testBasic() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/basic.kt");
    }

    @Test
    @TestMetadata("do_not_verify.kt")
    public void testDo_not_verify() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/do_not_verify.kt");
    }

    @Test
    @TestMetadata("extension_properties.kt")
    public void testExtension_properties() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/extension_properties.kt");
    }

    @Test
    @TestMetadata("full_viper_dump.kt")
    public void testFull_viper_dump() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/full_viper_dump.kt");
    }

    @Test
    @TestMetadata("function_object.kt")
    public void testFunction_object() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/function_object.kt");
    }

    @Test
    @TestMetadata("function_overloading.kt")
    public void testFunction_overloading() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/function_overloading.kt");
    }

    @Test
    @TestMetadata("havoc.kt")
    public void testHavoc() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/havoc.kt");
    }

    @Test
    @TestMetadata("multiple_receivers.kt")
    public void testMultiple_receivers() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/multiple_receivers.kt");
    }

    @Test
    @TestMetadata("old.kt")
    public void testOld() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/old.kt");
    }

    @Test
    @TestMetadata("shadowing.kt")
    public void testShadowing() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/shadowing.kt");
    }

    @Test
    @TestMetadata("unit_return_type.kt")
    public void testUnit_return_type() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/unit_return_type.kt");
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/classes")
    @TestDataPath("$PROJECT_ROOT")
    public class Classes {
      @Test
      @TestMetadata("acc_precondition.kt")
      public void testAcc_precondition() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/acc_precondition.kt");
      }

      @Test
      public void testAllFilesPresentInClasses() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/classes"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("inheritance.kt")
      public void testInheritance() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/inheritance.kt");
      }

      @Test
      @TestMetadata("inheritance_fields.kt")
      public void testInheritance_fields() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/inheritance_fields.kt");
      }

      @Test
      @TestMetadata("interfaces.kt")
      public void testInterfaces() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/interfaces.kt");
      }

      @Test
      @TestMetadata("manual_permissions.kt")
      public void testManual_permissions() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/manual_permissions.kt");
      }

      @Test
      @TestMetadata("member_functions.kt")
      public void testMember_functions() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/member_functions.kt");
      }

      @Test
      @TestMetadata("override_properties_types.kt")
      public void testOverride_properties_types() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/override_properties_types.kt");
      }

      @Test
      @TestMetadata("predicates.kt")
      public void testPredicates() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/predicates.kt");
      }

      @Test
      @TestMetadata("predicates_access.kt")
      public void testPredicates_access() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/predicates_access.kt");
      }

      @Test
      @TestMetadata("primary_constructors.kt")
      public void testPrimary_constructors() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/primary_constructors.kt");
      }

      @Test
      @TestMetadata("private_properties.kt")
      public void testPrivate_properties() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/private_properties.kt");
      }

      @Test
      @TestMetadata("property_accessors.kt")
      public void testProperty_accessors() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/property_accessors.kt");
      }

      @Test
      @TestMetadata("secondary_constructors.kt")
      public void testSecondary_constructors() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/secondary_constructors.kt");
      }

      @Test
      @TestMetadata("subtyping.kt")
      public void testSubtyping() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/subtyping.kt");
      }

      @Test
      @TestMetadata("unique_fields.kt")
      public void testUnique_fields() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_fields.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/contracts")
    @TestDataPath("$PROJECT_ROOT")
    public class Contracts {
      @Test
      public void testAllFilesPresentInContracts() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/contracts"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Nested
      @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative")
      @TestDataPath("$PROJECT_ROOT")
      public class Negative {
        @Test
        public void testAllFilesPresentInNegative() {
          KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative"), Pattern.compile("^(.+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("as_type_contract.kt")
        public void testAs_type_contract() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/as_type_contract.kt");
        }

        @Test
        @TestMetadata("cond_effects.kt")
        public void testCond_effects() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/cond_effects.kt");
        }

        @Test
        @TestMetadata("contracts_with_receivers.kt")
        public void testContracts_with_receivers() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/contracts_with_receivers.kt");
        }

        @Test
        @TestMetadata("is_type_contract.kt")
        public void testIs_type_contract() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/is_type_contract.kt");
        }

        @Test
        @TestMetadata("list.kt")
        public void testList() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/list.kt");
        }

        @Test
        @TestMetadata("returns_booleans.kt")
        public void testReturns_booleans() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/returns_booleans.kt");
        }

        @Test
        @TestMetadata("returns_not_null.kt")
        public void testReturns_not_null() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/returns_not_null.kt");
        }

        @Test
        @TestMetadata("returns_null.kt")
        public void testReturns_null() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/returns_null.kt");
        }

        @Test
        @TestMetadata("viper_verify.kt")
        public void testViper_verify() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/viper_verify.kt");
        }
      }

      @Nested
      @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive")
      @TestDataPath("$PROJECT_ROOT")
      public class Positive {
        @Test
        public void testAllFilesPresentInPositive() {
          KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive"), Pattern.compile("^(.+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("as_type_contract.kt")
        public void testAs_type_contract() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive/as_type_contract.kt");
        }

        @Test
        @TestMetadata("contracts_with_receivers.kt")
        public void testContracts_with_receivers() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive/contracts_with_receivers.kt");
        }

        @Test
        @TestMetadata("is_type_contract.kt")
        public void testIs_type_contract() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive/is_type_contract.kt");
        }

        @Test
        @TestMetadata("returns_booleans.kt")
        public void testReturns_booleans() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive/returns_booleans.kt");
        }

        @Test
        @TestMetadata("returns_null.kt")
        public void testReturns_null() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive/returns_null.kt");
        }

        @Test
        @TestMetadata("simple.kt")
        public void testSimple() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive/simple.kt");
        }
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/control_flow")
    @TestDataPath("$PROJECT_ROOT")
    public class Control_flow {
      @Test
      public void testAllFilesPresentInControl_flow() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/control_flow"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("exp_side_effects.kt")
      public void testExp_side_effects() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/exp_side_effects.kt");
      }

      @Test
      @TestMetadata("function_call.kt")
      public void testFunction_call() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/function_call.kt");
      }

      @Test
      @TestMetadata("if.kt")
      public void testIf() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/if.kt");
      }

      @Test
      @TestMetadata("loops.kt")
      public void testLoops() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/loops.kt");
      }

      @Test
      @TestMetadata("non-local-returns.kt")
      public void testNon_local_returns() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/non-local-returns.kt");
      }

      @Test
      @TestMetadata("recursion.kt")
      public void testRecursion() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/recursion.kt");
      }

      @Test
      @TestMetadata("return_break_continue.kt")
      public void testReturn_break_continue() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/return_break_continue.kt");
      }

      @Test
      @TestMetadata("when.kt")
      public void testWhen() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/when.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/inlining")
    @TestDataPath("$PROJECT_ROOT")
    public class Inlining {
      @Test
      public void testAllFilesPresentInInlining() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/inlining"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("custom_run_functions.kt")
      public void testCustom_run_functions() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/custom_run_functions.kt");
      }

      @Test
      @TestMetadata("inline_returns.kt")
      public void testInline_returns() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/inline_returns.kt");
      }

      @Test
      @TestMetadata("lambdas.kt")
      public void testLambdas() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/lambdas.kt");
      }

      @Test
      @TestMetadata("scoped_receivers.kt")
      public void testScoped_receivers() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/scoped_receivers.kt");
      }

      @Test
      @TestMetadata("viper_casts_while_inlining.kt")
      public void testViper_casts_while_inlining() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/viper_casts_while_inlining.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/negative")
    @TestDataPath("$PROJECT_ROOT")
    public class Negative {
      @Test
      public void testAllFilesPresentInNegative() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/negative"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("binary_tree.kt")
      public void testBinary_tree() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/negative/binary_tree.kt");
      }

      @Test
      @TestMetadata("linked_list.kt")
      public void testLinked_list() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/negative/linked_list.kt");
      }

      @Test
      @TestMetadata("try_catch.kt")
      public void testTry_catch() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/negative/try_catch.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/operators")
    @TestDataPath("$PROJECT_ROOT")
    public class Operators {
      @Test
      public void testAllFilesPresentInOperators() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/operators"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/operators/basic.kt");
      }

      @Test
      @TestMetadata("elvis.kt")
      public void testElvis() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/operators/elvis.kt");
      }

      @Test
      @TestMetadata("safe_call.kt")
      public void testSafe_call() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/operators/safe_call.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/pure_functions")
    @TestDataPath("$PROJECT_ROOT")
    public class Pure_functions {
      @Test
      public void testAllFilesPresentInPure_functions() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/pure_functions"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("branching.kt")
      public void testBranching() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/branching.kt");
      }

      @Test
      @TestMetadata("heap_dependent_specifications.kt")
      public void testHeap_dependent_specifications() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/heap_dependent_specifications.kt");
      }

      @Test
      @TestMetadata("literal_returns.kt")
      public void testLiteral_returns() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/literal_returns.kt");
      }

      @Test
      @TestMetadata("local_variables.kt")
      public void testLocal_variables() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/local_variables.kt");
      }

      @Test
      @TestMetadata("operators.kt")
      public void testOperators() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/operators.kt");
      }

      @Test
      @TestMetadata("pure_function_with_heap_dependent_expressions.kt")
      public void testPure_function_with_heap_dependent_expressions() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/pure_function_with_heap_dependent_expressions.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/purity")
    @TestDataPath("$PROJECT_ROOT")
    public class Purity {
      @Test
      public void testAllFilesPresentInPurity() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/purity"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("assert_statements.kt")
      public void testAssert_statements() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/purity/assert_statements.kt");
      }

      @Test
      @TestMetadata("wrongly_annotated.kt")
      public void testWrongly_annotated() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/purity/wrongly_annotated.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/types")
    @TestDataPath("$PROJECT_ROOT")
    public class Types {
      @Test
      public void testAllFilesPresentInTypes() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/types"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("any.kt")
      public void testAny() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/types/any.kt");
      }

      @Test
      @TestMetadata("casts.kt")
      public void testCasts() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/types/casts.kt");
      }

      @Test
      @TestMetadata("generics.kt")
      public void testGenerics() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/types/generics.kt");
      }

      @Test
      @TestMetadata("nullable.kt")
      public void testNullable() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/types/nullable.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/user_invariants")
    @TestDataPath("$PROJECT_ROOT")
    public class User_invariants {
      @Test
      public void testAllFilesPresentInUser_invariants() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/user_invariants"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("and_or_then.kt")
      public void testAnd_or_then() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/and_or_then.kt");
      }

      @Test
      @TestMetadata("factorial.kt")
      public void testFactorial() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/factorial.kt");
      }

      @Test
      @TestMetadata("forall_with_triggers.kt")
      public void testForall_with_triggers() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/forall_with_triggers.kt");
      }

      @Test
      @TestMetadata("loops.kt")
      public void testLoops() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/loops.kt");
      }

      @Test
      @TestMetadata("simple_forall.kt")
      public void testSimple_forall() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/simple_forall.kt");
      }

      @Test
      @TestMetadata("simple_postcondition.kt")
      public void testSimple_postcondition() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/simple_postcondition.kt");
      }

      @Test
      @TestMetadata("simple_precondition.kt")
      public void testSimple_precondition() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/simple_precondition.kt");
      }

      @Test
      @TestMetadata("string_iterations.kt")
      public void testString_iterations() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/string_iterations.kt");
      }

      @Test
      @TestMetadata("strings_in_conditions.kt")
      public void testStrings_in_conditions() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/strings_in_conditions.kt");
      }

      @Test
      @TestMetadata("sum_of_1_to_n.kt")
      public void testSum_of_1_to_n() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/sum_of_1_to_n.kt");
      }
    }
  }
}
